name: InstallDependencies
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  k8sVersion:
    description: Kubernetes version to use when installing the toolchain
    default: "1.24.x"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      id: setup-go
      with:
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: "**/go.sum"
    - run: sudo chown "$USER" /usr/local
      shell: bash
    - if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      shell: bash
      run: K8S_VERSION=${{ inputs.k8sVersion }} make toolchain
