name: presubmit
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: make presubmit