name: presubmit
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: 1.31
    - run: make presubmit